# Generated by Django 4.2.3 on 2023-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_email_token_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
