# Generated by Django 4.2.3 on 2023-07-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alternative_mobile',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
