# Generated by Django 4.2.3 on 2023-07-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_useraddress_alternative_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
    ]
