# Generated by Django 4.2.3 on 2023-08-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_useraddress_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alternative_mobile',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
