# Generated by Django 4.2.3 on 2023-08-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_useraddress_alternative_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alternative_mobile',
            field=models.IntegerField(blank=True, max_length=11),
        ),
    ]
