# Generated by Django 4.2.3 on 2023-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_useraddress_alternative_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
