# Generated by Django 4.2.3 on 2023-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='img/none_user.jpg', null=True, upload_to='profile_images'),
        ),
    ]
