# Generated by Django 4.2.3 on 2023-09-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alternative_mobile',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
