# Generated by Django 4.2.3 on 2023-09-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_walletbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbook',
            name='increment',
            field=models.BooleanField(default=False),
        ),
    ]
