# Generated by Django 4.2.3 on 2023-07-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_multipleimages_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
