# Generated by Django 4.2.3 on 2023-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
