# Generated by Django 4.2.3 on 2023-07-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productvariant_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='product_id',
            new_name='product',
        ),
    ]
