# Generated by Django 4.2.3 on 2023-08-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='coupon_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
