# Generated by Django 4.2.3 on 2023-08-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_quandity_coupons_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
