# Generated by Django 4.2.3 on 2023-08-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_coupons_active_alter_coupons_free_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
