# Generated by Django 4.2.3 on 2023-08-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_coupons_valid_from_alter_coupons_valid_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images')),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('identifier', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('offer_detail', models.CharField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
