# Generated by Django 4.2.3 on 2023-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
