# Generated by Django 4.2.3 on 2023-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
