# Generated by Django 4.2.3 on 2023-09-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_review_created_review_dislike_review_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
