# Generated by Django 4.2.3 on 2023-07-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_is_available'),
        ('cart', '0003_cartitem_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='single_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
