# Generated by Django 4.2.3 on 2023-08-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_useraddress_alternative_mobile'),
        ('cart', '0011_remove_cart_coupon_remove_cart_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.useraddress'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
