# Generated by Django 4.2.3 on 2023-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_checkout_address_checkout_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='wallet',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
