# Generated by Django 4.2.3 on 2023-08-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_checkout_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
