# Generated by Django 4.2.3 on 2023-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_checkout_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='wallet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
