# Generated by Django 4.2.3 on 2023-08-08 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_coupons_valid_from_alter_coupons_valid_to'),
        ('order', '0002_payments_is_paid_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupons'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Order confirmed', 'Order confirmed'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
