# Generated by Django 4.2.3 on 2023-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderproduct_return_request_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Shipped', 'Shipped'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled')], default='Order confirmed', max_length=50),
        ),
    ]
