# Generated by Django 4.2.3 on 2023-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='return_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped'), ('Return requested', 'Return requested')], default='Order confirmed', max_length=50),
        ),
    ]
