# Generated by Django 4.2.3 on 2023-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderproduct_return_accept_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed')], default='Order confirmed', max_length=50),
        ),
    ]
