# Generated by Django 4.2.3 on 2023-08-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
