# Generated by Django 4.2.3 on 2023-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery')], default='Order confirmed', max_length=50),
        ),
    ]
