# Generated by Django 4.2.3 on 2023-08-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery')], default='Order confirmed', max_length=50),
        ),
    ]
