# Generated by Django 4.2.3 on 2023-08-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_wallet_amount_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery')], default='Order confirmed', max_length=50),
        ),
    ]
