# Generated by Django 4.2.3 on 2023-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
