# Generated by Django 4.2.3 on 2023-08-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_coupons_valid_from_alter_coupons_valid_to'),
        ('order', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupons'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing')], default='Order confirmed', max_length=50),
        ),
    ]
