# Generated by Django 4.2.3 on 2023-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Return requested', 'Return requested')], default='Order confirmed', max_length=50),
        ),
    ]
