# Generated by Django 4.2.3 on 2023-08-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed')], default='Order confirmed', max_length=50),
        ),
    ]
