# Generated by Django 4.2.3 on 2023-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order confirmed', max_length=50),
        ),
    ]
