# Generated by Django 4.2.3 on 2023-09-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Return processing', 'Return processing'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Order confirmed', max_length=50),
        ),
    ]
