# Generated by Django 4.2.3 on 2023-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Delivered', 'Delivered')], default='Order confirmed', max_length=50),
        ),
    ]
