# Generated by Django 4.2.3 on 2023-09-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested')], default='Order confirmed', max_length=50),
        ),
    ]
