# Generated by Django 4.2.3 on 2023-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
